# Generated by Django 2.2 on 2021-11-01 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0003_auto_20210826_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forumname', models.CharField(default='Forum1', max_length=200)),
                ('description', models.CharField(default='NULL', max_length=200)),
                ('visibility', models.CharField(default='PUBLIC', max_length=20)),
            ],
        ),
    ]
