# Generated by Django 2.2 on 2021-11-01 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0005_auto_20211101_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foruminfo',
            name='identifier',
        ),
    ]
