# Generated by Django 2.2 on 2021-11-12 12:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Owner', '0006_remove_foruminfo_identifier'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(default='NULL', max_length=200, unique=True)),
                ('type_decription', models.CharField(default='NULL', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_creation', models.DateField(default=datetime.date(2021, 11, 12))),
                ('event_description', models.CharField(default='NULL', max_length=200)),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.EventTypes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Owner.UserInfo')),
            ],
        ),
    ]
