# Generated by Django 2.2 on 2021-11-12 20:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20211112_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='date_of_event',
            field=models.DateField(default=datetime.date(2021, 11, 13)),
        ),
        migrations.AddField(
            model_name='events',
            name='event_name',
            field=models.CharField(default='NULL', max_length=200),
        ),
        migrations.AddField(
            model_name='events',
            name='event_venue',
            field=models.CharField(default='NULL', max_length=200),
        ),
        migrations.AddField(
            model_name='events',
            name='time_of_event',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
