# Generated by Django 2.2 on 2021-11-12 21:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20211113_0209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='time_of_event',
        ),
        migrations.AlterField(
            model_name='events',
            name='date_of_event',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
